language: erlang

# install the latest stable rebar
before_install:
   - wget https://github.com/rebar/rebar/wiki/rebar
   - chmod +x rebar

script: "./.travis-ci.sh"
otp_release:
   - 22.0
   - 21.3
   - 20.3
   - 19.3
